<?php

namespace health\LifestyleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * gLinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gLinksRepository extends EntityRepository
{
}
