<?php

namespace health\LifestyleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GreensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GreensRepository extends EntityRepository
{
}
