parameters:
    database_driver: pdo_mysql
    database_host: '50.62.209.8'
    database_port: 3306
    database_name: healthApp
    database_user: APSquared
    database_password: APSquared1234
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 6232749637906b8a5361b6de29d800698b23c4af
    database_path: null
