parameters:
    database_driver: pdo_mysql
    database_host: 'localhost' #'50.62.209.8' #'127.0.0.1'
    database_port: 8889 #3306
    database_name: healthdb #healthApp
    database_user: root #APSquared
    database_password: root #APSquared1234
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 6232749637906b8a5361b6de29d800698b23c4af
    database_path: null

