healthuser:
    resource: "@healthuserBundle/Resources/config/routing.yml"
    prefix:   /

health_resources:
   resource: "@healthResourcesBundle/Resources/config/routing.php"


health_admin:
    resource: "@healthAdminBundle/Resources/config/routing.php"
    prefix:   /

health_detox:
    resource: "@healthDetoxBundle/Resources/config/routing.php"
    prefix:   /

health_lifestyle:
    resource: "@healthLifestyleBundle/Resources/config/routing.php"
    prefix:   /

healthforum:
    resource: "@healthforumBundle/Resources/config/routing.yml"
    prefix:   /

healthhealth_user:
    path: /
    defaults: {_controller: healthhealthUserBundle:Default:index}

Contest:
    path: /contest
    defaults: {_controller: healthhealthUserBundle:Contest:show}

life:
  path: /lifestyle
  defaults: {_controller: healthhealthUserBundle:Life:show}

Exercise:
    path: /exercise
    defaults: {_controller: healthhealthUserBundle:Exercise:show}

Upper:
  path: /upperbody
  defaults: {_controller: healthhealthUserBundle:Upper:show}

Lower:
  path: /lowerbody
  defaults: {_controller: healthhealthUserBundle:Lower:show}

Midsection:
  path: /midsection
  defaults: {_controller: healthhealthUserBundle:Midsection:show}

Detox:
    path: /detox
    defaults: {_controller: healthDetoxBundle:Detox:show}

Flush:
    path: /flush
    defaults: {_controller: healthDetoxBundle:flush:show}

Liquid:
    path: /liquid
    defaults: {_controller: healthDetoxBundle:liquid:show}

Vegan:
    path: /vegan
    defaults: {_controller: healthDetoxBundle:vegan:show}

Forum:
    path: /forum
    defaults: {_controller: healthforumBundle:Forum:show }

Create:
    path: /newpost
    defaults: {_controller: healthforumBundle:Create:create }


Resource:
    path: /resource
    defaults: {_controller: healthResourcesBundle:Resource:show }

Finder:
      path: /findgym
      defaults: {_controller: healthResourcesBundle:Gym:show }

Sample:
    path: /healthsample
    defaults: {_controller: healthLifestyleBundle:Sample:show }

Greens:
    path: /greenlean
    defaults: {_controller: healthLifestyleBundle:Greens:show }

Cheat:
    path: /cheat-generator
    defaults: {_controller: healthLifestyleBundle:Cheat:show }

register_register:
    path: /register
    defaults: { _controller: healthuserBundle:Register:register }

account_create:
    path: /register/create
    defaults: { _controller: healthuserBundle:Register:create }

Login_login:
    path: /login
    defaults: { _controller: healthuserBundle:Login:index }

Login_logout:
    path: /logout
    defaults: { _controller: healthuserBundle:Login:logout }

Recover_recover:
    path: /recover
    defaults: { _controller: healthuserBundle:Recover:recover }

Recover_security:
    path: /recover/security
    defaults: { _controller: healthuserBundle:Recover:security }

Recover_password:
    path: /recover/password 
    defaults: { _controller: healthuserBundle:Recover:password }

User_cpassword:
    path: /cpassword 
    defaults: { _controller: healthuserBundle:User:cpassword }

Recipe_addrecipe:
    path: /addrecipe
    defaults: { _controller: healthuserBundle:Recipe:addrecipe }

Recipe_showrecipe:
    path: /showrecipe
    defaults: { _controller: healthuserBundle:Recipe:showrecipe }

Upload_upload:
    path: /upload 
    defaults: { _controller: healthuserBundle:Upload:upload }