health_lifestyle:
    resource: "@healthLifestyleBundle/Resources/config/routing.php"
    prefix:   /

healthforum:
    resource: "@healthforumBundle/Resources/config/routing.yml"
    prefix:   /

healthhealth_user:
    path: /
    defaults: {_controller: healthhealthUserBundle:Default:index}

life:
  path: /lifestyle
  defaults: {_controller: healthhealthUserBundle:Life:show}

Exercise:
    path: /exercise
    defaults: {_controller: healthhealthUserBundle:Exercise:show}