parameters:
#    healthforum.example.class: health\forumBundle\Example

services:
#    healthforum.example:
#        class: %healthforum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
