parameters:
#    healthhealth_user.example.class: health\healthUserBundle\Example

services:
#    healthhealth_user.example:
#        class: %healthhealth_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
