parameters:
#    healthuser.example.class: health\userBundle\Example

services:
#    healthuser.example:
#        class: %healthuser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
